puts "applying partitioning constraints generated by tapac"
write_checkpoint before_add_floorplan_constraints.dcp

# begin defining a slot
create_pblock CR_X4Y4_To_CR_X7Y7
resize_pblock CR_X4Y4_To_CR_X7Y7 -add CLOCKREGION_X4Y4:CLOCKREGION_X7Y7
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X4Y4_To_CR_X7Y7 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11


# begin defining a slot
create_pblock CR_X0Y0_To_CR_X3Y3
resize_pblock CR_X0Y0_To_CR_X3Y3 -add CLOCKREGION_X0Y0:CLOCKREGION_X3Y3
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X0Y0_To_CR_X3Y3 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11


# begin defining a slot
create_pblock CR_X4Y0_To_CR_X7Y3
resize_pblock CR_X4Y0_To_CR_X7Y3 -add CLOCKREGION_X4Y0:CLOCKREGION_X7Y3
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X4Y0_To_CR_X7Y3 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11


# begin defining a slot
create_pblock CR_X0Y4_To_CR_X3Y7
resize_pblock CR_X0Y4_To_CR_X3Y7 -add CLOCKREGION_X0Y4:CLOCKREGION_X3Y7
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X0Y4_To_CR_X3Y7 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11

add_cells_to_pblock [get_pblocks pblock_dynamic_SLR0] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/control_s_axi_U_slr_0
  pfm_top_i/dynamic_region/.*/inst/.*/tapa_state.*
} ]
add_cells_to_pblock [get_pblocks pblock_dynamic_SLR1] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/control_s_axi_U_slr_1
} ]
add_cells_to_pblock [get_pblocks pblock_dynamic_SLR2] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/control_s_axi_U_slr_2
} ]
add_cells_to_pblock [get_pblocks CR_X0Y4_To_CR_X3Y7] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_0
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_1
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_2
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_3
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_3__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_4
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_4__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_5
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_5__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_6
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_6__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_7
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L2_in_7__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_3
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_3__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_4
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_4__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_5
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_5__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_6
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_6__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_7
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_7__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L2_in_0
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L2_in_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L2_in_1
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L2_in_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_0
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_1
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_2
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_3
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_3__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_4
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_4__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_5
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_5__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_6
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_6__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_7
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_7__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_8
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_8__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_9
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_9__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_10
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_10__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_11
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_11__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_12
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_12__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_13
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_13__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_14
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_14__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_15
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_15__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_16
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_16__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_17
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_17__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_18
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_18__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_19
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_19__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_20
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_20__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_24
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_24__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_25
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_25__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_26
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_26__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_27
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_27__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_28
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_28__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L2_out_1
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L2_out_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L2_out_2
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L2_out_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_0
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_1
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_4
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_4__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_5
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_5__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_8
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_8__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_9
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_9__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_12
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_12__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_13
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_13__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_14
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_14__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_15
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_15__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_16
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_16__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_17
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_17__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_18
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_18__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_19
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_19__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_20
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_20__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_21
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_21__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_22
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_22__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_23
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_23__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_24
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_24__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_25
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_25__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_26
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_26__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_27
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_27__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_28
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_28__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_29
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_29__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_30
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_30__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_31
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_31__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_0/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_5/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_6/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_7/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_8/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_0_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_0_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_0_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_1_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_1_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_1_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_2_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_2_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_2_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_3_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_3_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_3_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_3_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_3_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_4_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_4_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_4_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_4_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_4_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_5_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_5_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_5_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_5_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_5_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_6_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_6_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_6_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_6_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_6_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_7_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_7_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_7_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_7_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_7_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_B_IO_L2_in_0/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_B_IO_L2_in_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_B_IO_L2_in_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_0_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_0_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_1_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_1_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_2_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_2_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_3_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_3_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_3_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_3_3/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_4_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_4_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_4_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_4_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_5_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_5_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_5_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_5_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_6_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_6_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_6_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_6_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_7_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_7_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_7_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_7_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_8_0/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_8_1/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_8_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_8_3/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_0_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_0_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_0_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_0_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_0_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_0_5/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_0_6/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_0_7/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_1_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_1_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_1_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_1_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_1_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_1_5/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_1_6/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_1_7/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_3/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_5/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_6/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_7/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_3/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_5/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_6/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_7/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L2_out_0/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L2_out_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L2_out_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_0_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_0_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_1_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_1_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_2_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_2_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_3_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_3_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_3_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_3_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_4_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_4_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_4_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_4_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_5_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_5_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_5_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_5_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_6_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_6_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_6_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_6_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_7_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_7_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_7_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_7_3/.*.unit
} ]
add_cells_to_pblock [get_pblocks CR_X0Y0_To_CR_X3Y3] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L3_in_0
  pfm_top_i/dynamic_region/.*/inst/.*/A_IO_L3_in_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L3_in_0
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L3_in_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L3_out_0
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L3_out_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_c_1
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_c_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_c_3
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_c_3__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_final_0
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_final_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_a_0
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_a_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_b_0
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_b_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_b_1
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_b_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_b_2
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_b_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_b_3
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_b_3__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_final_0
  pfm_top_i/dynamic_region/.*/inst/.*/Stream2Mmap_final_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_0/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_A_IO_L2_in_8/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_B_IO_L2_in_0/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_8_0/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_8_1/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_8_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_8_3/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L2_out_0/inst\\[1]\\.unit
} ]
add_cells_to_pblock [get_pblocks CR_X4Y4_To_CR_X7Y7] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_0
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_1
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_1__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_2
  pfm_top_i/dynamic_region/.*/inst/.*/A_PE_dummy_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L2_in_2
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L2_in_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L2_in_boundary_0
  pfm_top_i/dynamic_region/.*/inst/.*/B_IO_L2_in_boundary_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_21
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_21__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_22
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_22__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_23
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_23__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_29
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_29__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_30
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_30__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_31
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L1_out_31__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L2_out_0
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L2_out_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L2_out_boundary_0
  pfm_top_i/dynamic_region/.*/inst/.*/C_drain_IO_L2_out_boundary_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_2
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_2__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_3
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_3__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_6
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_6__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_7
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_7__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_10
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_10__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_11
  pfm_top_i/dynamic_region/.*/inst/.*/PE_wrapper_11__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_0_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_0_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_0_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_1_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_1_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_1_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_2_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_2_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_A_PE_2_4/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_B_IO_L2_in_2/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_B_IO_L2_in_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_0_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_0_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_1_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_1_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_2_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_2_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_3_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_B_PE_3_3/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_2_3/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_0/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_1/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L1_out_3_3/inst\\[1]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L2_out_2/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_C_drain_IO_L2_out_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_0_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_0_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_1_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_1_3/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_2_2/.*.unit
  pfm_top_i/dynamic_region/.*/inst/.*/fifo_C_drain_PE_2_3/.*.unit
} ]
add_cells_to_pblock [get_pblocks CR_X4Y0_To_CR_X7Y3] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_c_0
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_c_0__state.*
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_c_2
  pfm_top_i/dynamic_region/.*/inst/.*/Mmap2Stream_c_2__state.*
} ]
add_cells_to_pblock [get_pblocks CR_X4Y0_To_CR_X7Y3] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/itemp1/R_pipeline/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/itemp1/B_pipeline/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/itemp3/R_pipeline/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/itemp3/B_pipeline/inst\\[0]\\.unit
} ]
add_cells_to_pblock [get_pblocks CR_X0Y0_To_CR_X3Y3] [get_cells -regex {
  pfm_top_i/dynamic_region/.*/inst/itemp1/AR_pipeline/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/itemp1/AW_pipeline/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/itemp1/W_pipeline/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/itemp3/AR_pipeline/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/itemp3/AW_pipeline/inst\\[0]\\.unit
  pfm_top_i/dynamic_region/.*/inst/itemp3/W_pipeline/inst\\[0]\\.unit
} ]
foreach pblock [get_pblocks -regexp CR_X\\d+Y\\d+_To_CR_X\\d+Y\\d+] {
  if {[get_property CELL_COUNT $pblock] == 0} {
    puts "WARNING: delete empty pblock $pblock "
    delete_pblocks $pblock
  }
}
foreach pblock [get_pblocks] {
  report_utilization -pblocks $pblock
}