#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("searchSpace_0_read_addr_din", 65, hls_out, 0, "ap_fifo", "fifo_port_we", 134),
	Port_Property("searchSpace_0_read_addr_full_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 134),
	Port_Property("searchSpace_0_read_addr_write", 1, hls_out, 0, "ap_fifo", "fifo_data", 134),
	Port_Property("searchSpace_0_read_data_s_dout", 257, hls_in, 1, "ap_fifo", "fifo_port_we", 134),
	Port_Property("searchSpace_0_read_data_s_empty_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 134),
	Port_Property("searchSpace_0_read_data_s_read", 1, hls_out, 1, "ap_fifo", "fifo_data", 134),
	Port_Property("searchSpace_0_read_data_peek_dout", 257, hls_in, 2, "ap_fifo", "fifo_port_we", 1),
	Port_Property("searchSpace_0_read_data_peek_empty_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("searchSpace_0_read_data_peek_read", 1, hls_out, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("searchSpace_0_write_addr_din", 65, hls_out, 3, "ap_fifo", "fifo_port_we", 1),
	Port_Property("searchSpace_0_write_addr_full_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("searchSpace_0_write_addr_write", 1, hls_out, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("searchSpace_0_write_data_din", 257, hls_out, 4, "ap_fifo", "fifo_port_we", 1),
	Port_Property("searchSpace_0_write_data_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("searchSpace_0_write_data_write", 1, hls_out, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("searchSpace_0_write_resp_s_dout", 9, hls_in, 5, "ap_fifo", "fifo_port_we", 1),
	Port_Property("searchSpace_0_write_resp_s_empty_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 1),
	Port_Property("searchSpace_0_write_resp_s_read", 1, hls_out, 5, "ap_fifo", "fifo_data", 1),
	Port_Property("searchSpace_0_write_resp_peek_dout", 9, hls_in, 6, "ap_fifo", "fifo_port_we", 1),
	Port_Property("searchSpace_0_write_resp_peek_empty_n", 1, hls_in, 6, "ap_fifo", "fifo_status", 1),
	Port_Property("searchSpace_0_write_resp_peek_read", 1, hls_out, 6, "ap_fifo", "fifo_data", 1),
	Port_Property("start_id_0", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("out_dist_din", 45, hls_out, 8, "ap_fifo", "fifo_port_we", 2),
	Port_Property("out_dist_full_n", 1, hls_in, 8, "ap_fifo", "fifo_status", 2),
	Port_Property("out_dist_write", 1, hls_out, 8, "ap_fifo", "fifo_data", 2),
	Port_Property("out_id_din", 45, hls_out, 9, "ap_fifo", "fifo_port_we", 2),
	Port_Property("out_id_full_n", 1, hls_in, 9, "ap_fifo", "fifo_status", 2),
	Port_Property("out_id_write", 1, hls_out, 9, "ap_fifo", "fifo_data", 2),
};
const char* HLS_Design_Meta::dut_name = "krnl_partialKnn_wrapper_7";
