#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("a_s_dout", 33, hls_in, 0, "ap_fifo", "fifo_port_we", 2),
	Port_Property("a_s_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 2),
	Port_Property("a_s_read", 1, hls_out, 0, "ap_fifo", "fifo_data", 2),
	Port_Property("a_peek_dout", 33, hls_in, 1, "ap_fifo", "fifo_port_we", 1),
	Port_Property("a_peek_empty_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("a_peek_read", 1, hls_out, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("b_s_dout", 33, hls_in, 2, "ap_fifo", "fifo_port_we", 2),
	Port_Property("b_s_empty_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 2),
	Port_Property("b_s_read", 1, hls_out, 2, "ap_fifo", "fifo_data", 2),
	Port_Property("b_peek_dout", 33, hls_in, 3, "ap_fifo", "fifo_port_we", 1),
	Port_Property("b_peek_empty_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("b_peek_read", 1, hls_out, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("c_din", 33, hls_out, 4, "ap_fifo", "fifo_port_we", 2),
	Port_Property("c_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 2),
	Port_Property("c_write", 1, hls_out, 4, "ap_fifo", "fifo_data", 2),
	Port_Property("n", 64, hls_in, 5, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "Add";
