-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_globalSort_L3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_dist0_s_dout : IN STD_LOGIC_VECTOR (44 downto 0);
    in_dist0_s_empty_n : IN STD_LOGIC;
    in_dist0_s_read : OUT STD_LOGIC;
    in_dist0_peek_dout : IN STD_LOGIC_VECTOR (44 downto 0);
    in_dist0_peek_empty_n : IN STD_LOGIC;
    in_dist0_peek_read : OUT STD_LOGIC;
    in_id0_s_dout : IN STD_LOGIC_VECTOR (44 downto 0);
    in_id0_s_empty_n : IN STD_LOGIC;
    in_id0_s_read : OUT STD_LOGIC;
    in_id0_peek_dout : IN STD_LOGIC_VECTOR (44 downto 0);
    in_id0_peek_empty_n : IN STD_LOGIC;
    in_id0_peek_read : OUT STD_LOGIC;
    in_dist1_s_dout : IN STD_LOGIC_VECTOR (44 downto 0);
    in_dist1_s_empty_n : IN STD_LOGIC;
    in_dist1_s_read : OUT STD_LOGIC;
    in_dist1_peek_dout : IN STD_LOGIC_VECTOR (44 downto 0);
    in_dist1_peek_empty_n : IN STD_LOGIC;
    in_dist1_peek_read : OUT STD_LOGIC;
    in_id1_s_dout : IN STD_LOGIC_VECTOR (44 downto 0);
    in_id1_s_empty_n : IN STD_LOGIC;
    in_id1_s_read : OUT STD_LOGIC;
    in_id1_peek_dout : IN STD_LOGIC_VECTOR (44 downto 0);
    in_id1_peek_empty_n : IN STD_LOGIC;
    in_id1_peek_read : OUT STD_LOGIC;
    output_knnDist_read_addr_din : OUT STD_LOGIC_VECTOR (64 downto 0);
    output_knnDist_read_addr_full_n : IN STD_LOGIC;
    output_knnDist_read_addr_write : OUT STD_LOGIC;
    output_knnDist_read_data_s_dout : IN STD_LOGIC_VECTOR (32 downto 0);
    output_knnDist_read_data_s_empty_n : IN STD_LOGIC;
    output_knnDist_read_data_s_read : OUT STD_LOGIC;
    output_knnDist_read_data_peek_dout : IN STD_LOGIC_VECTOR (32 downto 0);
    output_knnDist_read_data_peek_empty_n : IN STD_LOGIC;
    output_knnDist_read_data_peek_read : OUT STD_LOGIC;
    output_knnDist_write_addr_din : OUT STD_LOGIC_VECTOR (64 downto 0);
    output_knnDist_write_addr_full_n : IN STD_LOGIC;
    output_knnDist_write_addr_write : OUT STD_LOGIC;
    output_knnDist_write_data_din : OUT STD_LOGIC_VECTOR (32 downto 0);
    output_knnDist_write_data_full_n : IN STD_LOGIC;
    output_knnDist_write_data_write : OUT STD_LOGIC;
    output_knnDist_write_resp_s_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    output_knnDist_write_resp_s_empty_n : IN STD_LOGIC;
    output_knnDist_write_resp_s_read : OUT STD_LOGIC;
    output_knnDist_write_resp_peek_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    output_knnDist_write_resp_peek_empty_n : IN STD_LOGIC;
    output_knnDist_write_resp_peek_read : OUT STD_LOGIC;
    output_knnId_read_addr_din : OUT STD_LOGIC_VECTOR (64 downto 0);
    output_knnId_read_addr_full_n : IN STD_LOGIC;
    output_knnId_read_addr_write : OUT STD_LOGIC;
    output_knnId_read_data_s_dout : IN STD_LOGIC_VECTOR (32 downto 0);
    output_knnId_read_data_s_empty_n : IN STD_LOGIC;
    output_knnId_read_data_s_read : OUT STD_LOGIC;
    output_knnId_read_data_peek_dout : IN STD_LOGIC_VECTOR (32 downto 0);
    output_knnId_read_data_peek_empty_n : IN STD_LOGIC;
    output_knnId_read_data_peek_read : OUT STD_LOGIC;
    output_knnId_write_addr_din : OUT STD_LOGIC_VECTOR (64 downto 0);
    output_knnId_write_addr_full_n : IN STD_LOGIC;
    output_knnId_write_addr_write : OUT STD_LOGIC;
    output_knnId_write_data_din : OUT STD_LOGIC_VECTOR (32 downto 0);
    output_knnId_write_data_full_n : IN STD_LOGIC;
    output_knnId_write_data_write : OUT STD_LOGIC;
    output_knnId_write_resp_s_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    output_knnId_write_resp_s_empty_n : IN STD_LOGIC;
    output_knnId_write_resp_s_read : OUT STD_LOGIC;
    output_knnId_write_resp_peek_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    output_knnId_write_resp_peek_empty_n : IN STD_LOGIC;
    output_knnId_write_resp_peek_read : OUT STD_LOGIC );
end;


architecture behav of krnl_globalSort_L3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "krnl_globalSort_L3_krnl_globalSort_L3,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.330000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.187450,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3038,HLS_SYN_LUT=1380,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv65_0 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal output_dist_reg_1176 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal output_dist_1_reg_1181 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_dist_2_reg_1186 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_dist_3_reg_1191 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_dist_4_reg_1196 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_dist_5_reg_1201 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_dist_6_reg_1206 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_dist_7_reg_1211 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_dist_8_reg_1216 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_dist_9_reg_1221 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_reg_1226 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_1_reg_1231 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_2_reg_1236 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_3_reg_1241 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_4_reg_1246 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_5_reg_1251 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_6_reg_1256 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_7_reg_1261 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_8_reg_1266 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_id_9_reg_1271 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_done : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_idle : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_ready : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_in_dist0_s_read : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_in_dist1_s_read : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1928_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1928_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1827_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1827_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1726_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1726_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1625_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1625_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1524_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1524_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1423_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1423_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1322_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1322_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1221_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1221_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1120_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1120_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1019_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1019_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_918_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_918_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_817_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_817_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_716_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_716_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_615_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_615_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_514_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_514_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_413_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_413_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_312_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_312_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_211_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_211_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_110_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_110_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial1_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_done : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_idle : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_ready : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_in_id0_s_read : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_in_id1_s_read : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1948_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1948_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1847_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1847_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1746_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1746_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1645_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1645_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1544_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1544_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1443_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1443_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1342_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1342_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1241_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1241_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1140_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1140_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1039_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1039_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_938_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_938_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_837_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_837_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_736_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_736_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_635_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_635_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_534_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_534_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_433_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_433_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_332_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_332_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_231_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_231_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_130_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_130_out_ap_vld : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial29_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial29_out_ap_vld : STD_LOGIC;
    signal grp_seq_global_merge_L3_fu_476_ap_start : STD_LOGIC;
    signal grp_seq_global_merge_L3_fu_476_ap_done : STD_LOGIC;
    signal grp_seq_global_merge_L3_fu_476_ap_idle : STD_LOGIC;
    signal grp_seq_global_merge_L3_fu_476_ap_ready : STD_LOGIC;
    signal grp_seq_global_merge_L3_fu_476_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_8 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_11 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_12 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_13 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_14 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_15 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_16 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_17 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_18 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_seq_global_merge_L3_fu_476_ap_return_19 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_idle : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_ready : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_resp_s_read : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_resp_s_read : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_addr_din : STD_LOGIC_VECTOR (64 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_addr_write : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_data_din : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_data_write : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_addr_din : STD_LOGIC_VECTOR (64 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_addr_write : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_data_din : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_data_write : STD_LOGIC;
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_seq_global_merge_L3_fu_476_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component krnl_globalSort_L3_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_dist0_s_dout : IN STD_LOGIC_VECTOR (44 downto 0);
        in_dist0_s_empty_n : IN STD_LOGIC;
        in_dist0_s_read : OUT STD_LOGIC;
        in_dist1_s_dout : IN STD_LOGIC_VECTOR (44 downto 0);
        in_dist1_s_empty_n : IN STD_LOGIC;
        in_dist1_s_read : OUT STD_LOGIC;
        local_kNearstDist_partial_1928_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1928_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1827_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1827_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1726_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1726_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1625_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1625_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1524_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1524_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1423_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1423_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1322_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1322_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1221_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1221_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1120_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1120_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_1019_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_1019_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_918_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_918_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_817_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_817_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_716_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_716_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_615_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_615_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_514_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_514_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_413_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_413_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_312_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_312_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_211_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_211_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial_110_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial_110_out_ap_vld : OUT STD_LOGIC;
        local_kNearstDist_partial1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstDist_partial1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component krnl_globalSort_L3_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_id0_s_dout : IN STD_LOGIC_VECTOR (44 downto 0);
        in_id0_s_empty_n : IN STD_LOGIC;
        in_id0_s_read : OUT STD_LOGIC;
        in_id1_s_dout : IN STD_LOGIC_VECTOR (44 downto 0);
        in_id1_s_empty_n : IN STD_LOGIC;
        in_id1_s_read : OUT STD_LOGIC;
        local_kNearstId_partial_1948_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1948_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1847_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1847_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1746_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1746_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1645_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1645_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1544_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1544_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1443_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1443_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1342_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1342_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1241_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1241_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1140_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1140_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_1039_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_1039_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_938_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_938_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_837_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_837_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_736_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_736_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_635_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_635_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_534_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_534_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_433_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_433_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_332_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_332_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_231_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_231_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial_130_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial_130_out_ap_vld : OUT STD_LOGIC;
        local_kNearstId_partial29_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kNearstId_partial29_out_ap_vld : OUT STD_LOGIC );
    end component;


    component krnl_globalSort_L3_seq_global_merge_L3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read21 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read23 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read24 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read25 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read27 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read28 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read29 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read31 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read32 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read33 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read34 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read35 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read36 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read37 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read38 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read39 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component krnl_globalSort_L3_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_knnId_write_resp_s_dout : IN STD_LOGIC_VECTOR (8 downto 0);
        output_knnId_write_resp_s_empty_n : IN STD_LOGIC;
        output_knnId_write_resp_s_read : OUT STD_LOGIC;
        output_knnDist_write_resp_s_dout : IN STD_LOGIC_VECTOR (8 downto 0);
        output_knnDist_write_resp_s_empty_n : IN STD_LOGIC;
        output_knnDist_write_resp_s_read : OUT STD_LOGIC;
        output_knnDist_write_addr_din : OUT STD_LOGIC_VECTOR (64 downto 0);
        output_knnDist_write_addr_full_n : IN STD_LOGIC;
        output_knnDist_write_addr_write : OUT STD_LOGIC;
        output_knnDist_write_data_din : OUT STD_LOGIC_VECTOR (32 downto 0);
        output_knnDist_write_data_full_n : IN STD_LOGIC;
        output_knnDist_write_data_write : OUT STD_LOGIC;
        output_dist : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_dist_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_knnId_write_addr_din : OUT STD_LOGIC_VECTOR (64 downto 0);
        output_knnId_write_addr_full_n : IN STD_LOGIC;
        output_knnId_write_addr_write : OUT STD_LOGIC;
        output_knnId_write_data_din : OUT STD_LOGIC_VECTOR (32 downto 0);
        output_knnId_write_data_full_n : IN STD_LOGIC;
        output_knnId_write_data_write : OUT STD_LOGIC;
        output_id : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_id_9 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420 : component krnl_globalSort_L3_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start,
        ap_done => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_done,
        ap_idle => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_idle,
        ap_ready => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_ready,
        in_dist0_s_dout => in_dist0_s_dout,
        in_dist0_s_empty_n => in_dist0_s_empty_n,
        in_dist0_s_read => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_in_dist0_s_read,
        in_dist1_s_dout => in_dist1_s_dout,
        in_dist1_s_empty_n => in_dist1_s_empty_n,
        in_dist1_s_read => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_in_dist1_s_read,
        local_kNearstDist_partial_1928_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1928_out,
        local_kNearstDist_partial_1928_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1928_out_ap_vld,
        local_kNearstDist_partial_1827_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1827_out,
        local_kNearstDist_partial_1827_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1827_out_ap_vld,
        local_kNearstDist_partial_1726_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1726_out,
        local_kNearstDist_partial_1726_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1726_out_ap_vld,
        local_kNearstDist_partial_1625_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1625_out,
        local_kNearstDist_partial_1625_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1625_out_ap_vld,
        local_kNearstDist_partial_1524_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1524_out,
        local_kNearstDist_partial_1524_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1524_out_ap_vld,
        local_kNearstDist_partial_1423_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1423_out,
        local_kNearstDist_partial_1423_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1423_out_ap_vld,
        local_kNearstDist_partial_1322_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1322_out,
        local_kNearstDist_partial_1322_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1322_out_ap_vld,
        local_kNearstDist_partial_1221_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1221_out,
        local_kNearstDist_partial_1221_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1221_out_ap_vld,
        local_kNearstDist_partial_1120_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1120_out,
        local_kNearstDist_partial_1120_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1120_out_ap_vld,
        local_kNearstDist_partial_1019_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1019_out,
        local_kNearstDist_partial_1019_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1019_out_ap_vld,
        local_kNearstDist_partial_918_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_918_out,
        local_kNearstDist_partial_918_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_918_out_ap_vld,
        local_kNearstDist_partial_817_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_817_out,
        local_kNearstDist_partial_817_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_817_out_ap_vld,
        local_kNearstDist_partial_716_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_716_out,
        local_kNearstDist_partial_716_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_716_out_ap_vld,
        local_kNearstDist_partial_615_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_615_out,
        local_kNearstDist_partial_615_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_615_out_ap_vld,
        local_kNearstDist_partial_514_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_514_out,
        local_kNearstDist_partial_514_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_514_out_ap_vld,
        local_kNearstDist_partial_413_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_413_out,
        local_kNearstDist_partial_413_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_413_out_ap_vld,
        local_kNearstDist_partial_312_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_312_out,
        local_kNearstDist_partial_312_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_312_out_ap_vld,
        local_kNearstDist_partial_211_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_211_out,
        local_kNearstDist_partial_211_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_211_out_ap_vld,
        local_kNearstDist_partial_110_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_110_out,
        local_kNearstDist_partial_110_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_110_out_ap_vld,
        local_kNearstDist_partial1_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial1_out,
        local_kNearstDist_partial1_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial1_out_ap_vld);

    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448 : component krnl_globalSort_L3_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start,
        ap_done => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_done,
        ap_idle => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_idle,
        ap_ready => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_ready,
        in_id0_s_dout => in_id0_s_dout,
        in_id0_s_empty_n => in_id0_s_empty_n,
        in_id0_s_read => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_in_id0_s_read,
        in_id1_s_dout => in_id1_s_dout,
        in_id1_s_empty_n => in_id1_s_empty_n,
        in_id1_s_read => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_in_id1_s_read,
        local_kNearstId_partial_1948_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1948_out,
        local_kNearstId_partial_1948_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1948_out_ap_vld,
        local_kNearstId_partial_1847_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1847_out,
        local_kNearstId_partial_1847_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1847_out_ap_vld,
        local_kNearstId_partial_1746_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1746_out,
        local_kNearstId_partial_1746_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1746_out_ap_vld,
        local_kNearstId_partial_1645_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1645_out,
        local_kNearstId_partial_1645_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1645_out_ap_vld,
        local_kNearstId_partial_1544_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1544_out,
        local_kNearstId_partial_1544_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1544_out_ap_vld,
        local_kNearstId_partial_1443_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1443_out,
        local_kNearstId_partial_1443_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1443_out_ap_vld,
        local_kNearstId_partial_1342_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1342_out,
        local_kNearstId_partial_1342_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1342_out_ap_vld,
        local_kNearstId_partial_1241_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1241_out,
        local_kNearstId_partial_1241_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1241_out_ap_vld,
        local_kNearstId_partial_1140_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1140_out,
        local_kNearstId_partial_1140_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1140_out_ap_vld,
        local_kNearstId_partial_1039_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1039_out,
        local_kNearstId_partial_1039_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1039_out_ap_vld,
        local_kNearstId_partial_938_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_938_out,
        local_kNearstId_partial_938_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_938_out_ap_vld,
        local_kNearstId_partial_837_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_837_out,
        local_kNearstId_partial_837_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_837_out_ap_vld,
        local_kNearstId_partial_736_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_736_out,
        local_kNearstId_partial_736_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_736_out_ap_vld,
        local_kNearstId_partial_635_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_635_out,
        local_kNearstId_partial_635_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_635_out_ap_vld,
        local_kNearstId_partial_534_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_534_out,
        local_kNearstId_partial_534_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_534_out_ap_vld,
        local_kNearstId_partial_433_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_433_out,
        local_kNearstId_partial_433_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_433_out_ap_vld,
        local_kNearstId_partial_332_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_332_out,
        local_kNearstId_partial_332_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_332_out_ap_vld,
        local_kNearstId_partial_231_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_231_out,
        local_kNearstId_partial_231_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_231_out_ap_vld,
        local_kNearstId_partial_130_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_130_out,
        local_kNearstId_partial_130_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_130_out_ap_vld,
        local_kNearstId_partial29_out => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial29_out,
        local_kNearstId_partial29_out_ap_vld => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial29_out_ap_vld);

    grp_seq_global_merge_L3_fu_476 : component krnl_globalSort_L3_seq_global_merge_L3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_seq_global_merge_L3_fu_476_ap_start,
        ap_done => grp_seq_global_merge_L3_fu_476_ap_done,
        ap_idle => grp_seq_global_merge_L3_fu_476_ap_idle,
        ap_ready => grp_seq_global_merge_L3_fu_476_ap_ready,
        p_read => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial1_out,
        p_read1 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_110_out,
        p_read2 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_211_out,
        p_read3 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_312_out,
        p_read4 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_413_out,
        p_read5 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_514_out,
        p_read6 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_615_out,
        p_read7 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_716_out,
        p_read8 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_817_out,
        p_read9 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_918_out,
        p_read10 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1019_out,
        p_read11 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1120_out,
        p_read12 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1221_out,
        p_read13 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1322_out,
        p_read14 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1423_out,
        p_read15 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1524_out,
        p_read16 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1625_out,
        p_read17 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1726_out,
        p_read18 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1827_out,
        p_read19 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_local_kNearstDist_partial_1928_out,
        p_read20 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial29_out,
        p_read21 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_130_out,
        p_read22 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_231_out,
        p_read23 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_332_out,
        p_read24 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_433_out,
        p_read25 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_534_out,
        p_read26 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_635_out,
        p_read27 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_736_out,
        p_read28 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_837_out,
        p_read29 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_938_out,
        p_read30 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1039_out,
        p_read31 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1140_out,
        p_read32 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1241_out,
        p_read33 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1342_out,
        p_read34 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1443_out,
        p_read35 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1544_out,
        p_read36 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1645_out,
        p_read37 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1746_out,
        p_read38 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1847_out,
        p_read39 => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_local_kNearstId_partial_1948_out,
        ap_return_0 => grp_seq_global_merge_L3_fu_476_ap_return_0,
        ap_return_1 => grp_seq_global_merge_L3_fu_476_ap_return_1,
        ap_return_2 => grp_seq_global_merge_L3_fu_476_ap_return_2,
        ap_return_3 => grp_seq_global_merge_L3_fu_476_ap_return_3,
        ap_return_4 => grp_seq_global_merge_L3_fu_476_ap_return_4,
        ap_return_5 => grp_seq_global_merge_L3_fu_476_ap_return_5,
        ap_return_6 => grp_seq_global_merge_L3_fu_476_ap_return_6,
        ap_return_7 => grp_seq_global_merge_L3_fu_476_ap_return_7,
        ap_return_8 => grp_seq_global_merge_L3_fu_476_ap_return_8,
        ap_return_9 => grp_seq_global_merge_L3_fu_476_ap_return_9,
        ap_return_10 => grp_seq_global_merge_L3_fu_476_ap_return_10,
        ap_return_11 => grp_seq_global_merge_L3_fu_476_ap_return_11,
        ap_return_12 => grp_seq_global_merge_L3_fu_476_ap_return_12,
        ap_return_13 => grp_seq_global_merge_L3_fu_476_ap_return_13,
        ap_return_14 => grp_seq_global_merge_L3_fu_476_ap_return_14,
        ap_return_15 => grp_seq_global_merge_L3_fu_476_ap_return_15,
        ap_return_16 => grp_seq_global_merge_L3_fu_476_ap_return_16,
        ap_return_17 => grp_seq_global_merge_L3_fu_476_ap_return_17,
        ap_return_18 => grp_seq_global_merge_L3_fu_476_ap_return_18,
        ap_return_19 => grp_seq_global_merge_L3_fu_476_ap_return_19);

    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520 : component krnl_globalSort_L3_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start,
        ap_done => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done,
        ap_idle => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_idle,
        ap_ready => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_ready,
        output_knnId_write_resp_s_dout => output_knnId_write_resp_s_dout,
        output_knnId_write_resp_s_empty_n => output_knnId_write_resp_s_empty_n,
        output_knnId_write_resp_s_read => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_resp_s_read,
        output_knnDist_write_resp_s_dout => output_knnDist_write_resp_s_dout,
        output_knnDist_write_resp_s_empty_n => output_knnDist_write_resp_s_empty_n,
        output_knnDist_write_resp_s_read => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_resp_s_read,
        output_knnDist_write_addr_din => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_addr_din,
        output_knnDist_write_addr_full_n => output_knnDist_write_addr_full_n,
        output_knnDist_write_addr_write => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_addr_write,
        output_knnDist_write_data_din => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_data_din,
        output_knnDist_write_data_full_n => output_knnDist_write_data_full_n,
        output_knnDist_write_data_write => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_data_write,
        output_dist => output_dist_reg_1176,
        output_dist_1 => output_dist_1_reg_1181,
        output_dist_2 => output_dist_2_reg_1186,
        output_dist_3 => output_dist_3_reg_1191,
        output_dist_4 => output_dist_4_reg_1196,
        output_dist_5 => output_dist_5_reg_1201,
        output_dist_6 => output_dist_6_reg_1206,
        output_dist_7 => output_dist_7_reg_1211,
        output_dist_8 => output_dist_8_reg_1216,
        output_dist_9 => output_dist_9_reg_1221,
        output_knnId_write_addr_din => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_addr_din,
        output_knnId_write_addr_full_n => output_knnId_write_addr_full_n,
        output_knnId_write_addr_write => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_addr_write,
        output_knnId_write_data_din => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_data_din,
        output_knnId_write_data_full_n => output_knnId_write_data_full_n,
        output_knnId_write_data_write => grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_data_write,
        output_id => output_id_reg_1226,
        output_id_1 => output_id_1_reg_1231,
        output_id_2 => output_id_2_reg_1236,
        output_id_3 => output_id_3_reg_1241,
        output_id_4 => output_id_4_reg_1246,
        output_id_5 => output_id_5_reg_1251,
        output_id_6 => output_id_6_reg_1256,
        output_id_7 => output_id_7_reg_1261,
        output_id_8 => output_id_8_reg_1266,
        output_id_9 => output_id_9_reg_1271);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_ready = ap_const_logic_1)) then 
                    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_ready = ap_const_logic_1)) then 
                    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start_reg <= ap_const_logic_0;
            else
                if (((grp_seq_global_merge_L3_fu_476_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_ready = ap_const_logic_1)) then 
                    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_seq_global_merge_L3_fu_476_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_seq_global_merge_L3_fu_476_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_seq_global_merge_L3_fu_476_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_seq_global_merge_L3_fu_476_ap_ready = ap_const_logic_1)) then 
                    grp_seq_global_merge_L3_fu_476_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                output_dist_1_reg_1181 <= grp_seq_global_merge_L3_fu_476_ap_return_1;
                output_dist_2_reg_1186 <= grp_seq_global_merge_L3_fu_476_ap_return_2;
                output_dist_3_reg_1191 <= grp_seq_global_merge_L3_fu_476_ap_return_3;
                output_dist_4_reg_1196 <= grp_seq_global_merge_L3_fu_476_ap_return_4;
                output_dist_5_reg_1201 <= grp_seq_global_merge_L3_fu_476_ap_return_5;
                output_dist_6_reg_1206 <= grp_seq_global_merge_L3_fu_476_ap_return_6;
                output_dist_7_reg_1211 <= grp_seq_global_merge_L3_fu_476_ap_return_7;
                output_dist_8_reg_1216 <= grp_seq_global_merge_L3_fu_476_ap_return_8;
                output_dist_9_reg_1221 <= grp_seq_global_merge_L3_fu_476_ap_return_9;
                output_dist_reg_1176 <= grp_seq_global_merge_L3_fu_476_ap_return_0;
                output_id_1_reg_1231 <= grp_seq_global_merge_L3_fu_476_ap_return_11;
                output_id_2_reg_1236 <= grp_seq_global_merge_L3_fu_476_ap_return_12;
                output_id_3_reg_1241 <= grp_seq_global_merge_L3_fu_476_ap_return_13;
                output_id_4_reg_1246 <= grp_seq_global_merge_L3_fu_476_ap_return_14;
                output_id_5_reg_1251 <= grp_seq_global_merge_L3_fu_476_ap_return_15;
                output_id_6_reg_1256 <= grp_seq_global_merge_L3_fu_476_ap_return_16;
                output_id_7_reg_1261 <= grp_seq_global_merge_L3_fu_476_ap_return_17;
                output_id_8_reg_1266 <= grp_seq_global_merge_L3_fu_476_ap_return_18;
                output_id_9_reg_1271 <= grp_seq_global_merge_L3_fu_476_ap_return_19;
                output_id_reg_1226 <= grp_seq_global_merge_L3_fu_476_ap_return_10;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state8, grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_done, grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_done, grp_seq_global_merge_L3_fu_476_ap_done, grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_seq_global_merge_L3_fu_476_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_done)
    begin
        if ((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_done)
    begin
        if ((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_seq_global_merge_L3_fu_476_ap_done)
    begin
        if ((grp_seq_global_merge_L3_fu_476_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done)
    begin
        if ((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done, ap_CS_fsm_state9)
    begin
        if (((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done, ap_CS_fsm_state9)
    begin
        if (((grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_ap_start_reg;
    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_ap_start_reg;
    grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_ap_start_reg;
    grp_seq_global_merge_L3_fu_476_ap_start <= grp_seq_global_merge_L3_fu_476_ap_start_reg;
    in_dist0_peek_read <= ap_const_logic_0;

    in_dist0_s_read_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_in_dist0_s_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_dist0_s_read <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_in_dist0_s_read;
        else 
            in_dist0_s_read <= ap_const_logic_0;
        end if; 
    end process;

    in_dist1_peek_read <= ap_const_logic_0;

    in_dist1_s_read_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_in_dist1_s_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_dist1_s_read <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_875_1_fu_420_in_dist1_s_read;
        else 
            in_dist1_s_read <= ap_const_logic_0;
        end if; 
    end process;

    in_id0_peek_read <= ap_const_logic_0;

    in_id0_s_read_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_in_id0_s_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_id0_s_read <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_in_id0_s_read;
        else 
            in_id0_s_read <= ap_const_logic_0;
        end if; 
    end process;

    in_id1_peek_read <= ap_const_logic_0;

    in_id1_s_read_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_in_id1_s_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_id1_s_read <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_885_2_fu_448_in_id1_s_read;
        else 
            in_id1_s_read <= ap_const_logic_0;
        end if; 
    end process;

    output_knnDist_read_addr_din <= ap_const_lv65_0;
    output_knnDist_read_addr_write <= ap_const_logic_0;
    output_knnDist_read_data_peek_read <= ap_const_logic_0;
    output_knnDist_read_data_s_read <= ap_const_logic_0;
    output_knnDist_write_addr_din <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_addr_din;

    output_knnDist_write_addr_write_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_addr_write, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_knnDist_write_addr_write <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_addr_write;
        else 
            output_knnDist_write_addr_write <= ap_const_logic_0;
        end if; 
    end process;

    output_knnDist_write_data_din <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_data_din;

    output_knnDist_write_data_write_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_data_write, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_knnDist_write_data_write <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_data_write;
        else 
            output_knnDist_write_data_write <= ap_const_logic_0;
        end if; 
    end process;

    output_knnDist_write_resp_peek_read <= ap_const_logic_0;

    output_knnDist_write_resp_s_read_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_resp_s_read, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_knnDist_write_resp_s_read <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnDist_write_resp_s_read;
        else 
            output_knnDist_write_resp_s_read <= ap_const_logic_0;
        end if; 
    end process;

    output_knnId_read_addr_din <= ap_const_lv65_0;
    output_knnId_read_addr_write <= ap_const_logic_0;
    output_knnId_read_data_peek_read <= ap_const_logic_0;
    output_knnId_read_data_s_read <= ap_const_logic_0;
    output_knnId_write_addr_din <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_addr_din;

    output_knnId_write_addr_write_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_addr_write, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_knnId_write_addr_write <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_addr_write;
        else 
            output_knnId_write_addr_write <= ap_const_logic_0;
        end if; 
    end process;

    output_knnId_write_data_din <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_data_din;

    output_knnId_write_data_write_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_data_write, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_knnId_write_data_write <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_data_write;
        else 
            output_knnId_write_data_write <= ap_const_logic_0;
        end if; 
    end process;

    output_knnId_write_resp_peek_read <= ap_const_logic_0;

    output_knnId_write_resp_s_read_assign_proc : process(grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_resp_s_read, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_knnId_write_resp_s_read <= grp_krnl_globalSort_L3_Pipeline_VITIS_LOOP_895_3_fu_520_output_knnId_write_resp_s_read;
        else 
            output_knnId_write_resp_s_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
