// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Mmap2Stream_Mmap2Stream,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.433090,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=975,HLS_SYN_LUT=1500,HLS_VERSION=2022_1}" *)

module Mmap2Stream (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_mmap_AWVALID,
        m_axi_mmap_AWREADY,
        m_axi_mmap_AWADDR,
        m_axi_mmap_AWID,
        m_axi_mmap_AWLEN,
        m_axi_mmap_AWSIZE,
        m_axi_mmap_AWBURST,
        m_axi_mmap_AWLOCK,
        m_axi_mmap_AWCACHE,
        m_axi_mmap_AWPROT,
        m_axi_mmap_AWQOS,
        m_axi_mmap_AWREGION,
        m_axi_mmap_AWUSER,
        m_axi_mmap_WVALID,
        m_axi_mmap_WREADY,
        m_axi_mmap_WDATA,
        m_axi_mmap_WSTRB,
        m_axi_mmap_WLAST,
        m_axi_mmap_WID,
        m_axi_mmap_WUSER,
        m_axi_mmap_ARVALID,
        m_axi_mmap_ARREADY,
        m_axi_mmap_ARADDR,
        m_axi_mmap_ARID,
        m_axi_mmap_ARLEN,
        m_axi_mmap_ARSIZE,
        m_axi_mmap_ARBURST,
        m_axi_mmap_ARLOCK,
        m_axi_mmap_ARCACHE,
        m_axi_mmap_ARPROT,
        m_axi_mmap_ARQOS,
        m_axi_mmap_ARREGION,
        m_axi_mmap_ARUSER,
        m_axi_mmap_RVALID,
        m_axi_mmap_RREADY,
        m_axi_mmap_RDATA,
        m_axi_mmap_RLAST,
        m_axi_mmap_RID,
        m_axi_mmap_RUSER,
        m_axi_mmap_RRESP,
        m_axi_mmap_BVALID,
        m_axi_mmap_BREADY,
        m_axi_mmap_BRESP,
        m_axi_mmap_BID,
        m_axi_mmap_BUSER,
        mmap_offset,
        n,
        stream_din,
        stream_full_n,
        stream_write
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;
parameter    C_M_AXI_MMAP_ID_WIDTH = 1;
parameter    C_M_AXI_MMAP_ADDR_WIDTH = 64;
parameter    C_M_AXI_MMAP_DATA_WIDTH = 32;
parameter    C_M_AXI_MMAP_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_WUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_RUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_BUSER_WIDTH = 1;
parameter    C_M_AXI_MMAP_USER_VALUE = 0;
parameter    C_M_AXI_MMAP_PROT_VALUE = 0;
parameter    C_M_AXI_MMAP_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_MMAP_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_mmap_AWVALID;
input   m_axi_mmap_AWREADY;
output  [C_M_AXI_MMAP_ADDR_WIDTH - 1:0] m_axi_mmap_AWADDR;
output  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_AWID;
output  [7:0] m_axi_mmap_AWLEN;
output  [2:0] m_axi_mmap_AWSIZE;
output  [1:0] m_axi_mmap_AWBURST;
output  [1:0] m_axi_mmap_AWLOCK;
output  [3:0] m_axi_mmap_AWCACHE;
output  [2:0] m_axi_mmap_AWPROT;
output  [3:0] m_axi_mmap_AWQOS;
output  [3:0] m_axi_mmap_AWREGION;
output  [C_M_AXI_MMAP_AWUSER_WIDTH - 1:0] m_axi_mmap_AWUSER;
output   m_axi_mmap_WVALID;
input   m_axi_mmap_WREADY;
output  [C_M_AXI_MMAP_DATA_WIDTH - 1:0] m_axi_mmap_WDATA;
output  [C_M_AXI_MMAP_WSTRB_WIDTH - 1:0] m_axi_mmap_WSTRB;
output   m_axi_mmap_WLAST;
output  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_WID;
output  [C_M_AXI_MMAP_WUSER_WIDTH - 1:0] m_axi_mmap_WUSER;
output   m_axi_mmap_ARVALID;
input   m_axi_mmap_ARREADY;
output  [C_M_AXI_MMAP_ADDR_WIDTH - 1:0] m_axi_mmap_ARADDR;
output  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_ARID;
output  [7:0] m_axi_mmap_ARLEN;
output  [2:0] m_axi_mmap_ARSIZE;
output  [1:0] m_axi_mmap_ARBURST;
output  [1:0] m_axi_mmap_ARLOCK;
output  [3:0] m_axi_mmap_ARCACHE;
output  [2:0] m_axi_mmap_ARPROT;
output  [3:0] m_axi_mmap_ARQOS;
output  [3:0] m_axi_mmap_ARREGION;
output  [C_M_AXI_MMAP_ARUSER_WIDTH - 1:0] m_axi_mmap_ARUSER;
input   m_axi_mmap_RVALID;
output   m_axi_mmap_RREADY;
input  [C_M_AXI_MMAP_DATA_WIDTH - 1:0] m_axi_mmap_RDATA;
input   m_axi_mmap_RLAST;
input  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_RID;
input  [C_M_AXI_MMAP_RUSER_WIDTH - 1:0] m_axi_mmap_RUSER;
input  [1:0] m_axi_mmap_RRESP;
input   m_axi_mmap_BVALID;
output   m_axi_mmap_BREADY;
input  [1:0] m_axi_mmap_BRESP;
input  [C_M_AXI_MMAP_ID_WIDTH - 1:0] m_axi_mmap_BID;
input  [C_M_AXI_MMAP_BUSER_WIDTH - 1:0] m_axi_mmap_BUSER;
input  [63:0] mmap_offset;
input  [63:0] n;
output  [64:0] stream_din;
input   stream_full_n;
output   stream_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[64:0] stream_din;
reg stream_write;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    mmap_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [0:0] icmp_ln13_reg_153;
reg    stream_blk_n;
wire    ap_CS_fsm_state11;
wire   [0:0] icmp_ln13_fu_108_p2;
wire  signed [61:0] trunc_ln13_1_fu_114_p4;
reg   [61:0] trunc_ln13_1_reg_157;
wire   [31:0] shl_ln_fu_138_p3;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_done;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_idle;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_ready;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWVALID;
wire   [63:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWADDR;
wire   [0:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWID;
wire   [31:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWLEN;
wire   [2:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWSIZE;
wire   [1:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWBURST;
wire   [1:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWLOCK;
wire   [3:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWCACHE;
wire   [2:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWPROT;
wire   [3:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWQOS;
wire   [3:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWREGION;
wire   [0:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWUSER;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WVALID;
wire   [31:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WDATA;
wire   [3:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WSTRB;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WLAST;
wire   [0:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WID;
wire   [0:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WUSER;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARVALID;
wire   [63:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARADDR;
wire   [0:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARID;
wire   [31:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARLEN;
wire   [2:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARSIZE;
wire   [1:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARBURST;
wire   [1:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARLOCK;
wire   [3:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARCACHE;
wire   [2:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARPROT;
wire   [3:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARQOS;
wire   [3:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARREGION;
wire   [0:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARUSER;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_RREADY;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_BREADY;
wire   [64:0] grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_stream_din;
wire    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_stream_write;
wire    mmap_AWREADY;
wire    mmap_WREADY;
reg    mmap_ARVALID;
wire    mmap_ARREADY;
reg   [63:0] mmap_ARADDR;
reg   [31:0] mmap_ARLEN;
wire    mmap_RVALID;
reg    mmap_RREADY;
wire   [31:0] mmap_RDATA;
wire   [8:0] mmap_RFIFONUM;
wire    mmap_BVALID;
reg    grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [10:0] ap_NS_fsm;
wire    ap_NS_fsm_state9;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire  signed [63:0] sext_ln13_fu_124_p1;
reg    ap_block_state2_io;
wire   [30:0] trunc_ln13_fu_135_p1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start_reg = 1'b0;
end

Mmap2Stream_Mmap2Stream_Pipeline_VITIS_LOOP_13_1 grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start),
    .ap_done(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_done),
    .ap_idle(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_idle),
    .ap_ready(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_ready),
    .m_axi_mmap_AWVALID(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWVALID),
    .m_axi_mmap_AWREADY(1'b0),
    .m_axi_mmap_AWADDR(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWADDR),
    .m_axi_mmap_AWID(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWID),
    .m_axi_mmap_AWLEN(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWLEN),
    .m_axi_mmap_AWSIZE(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWSIZE),
    .m_axi_mmap_AWBURST(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWBURST),
    .m_axi_mmap_AWLOCK(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWLOCK),
    .m_axi_mmap_AWCACHE(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWCACHE),
    .m_axi_mmap_AWPROT(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWPROT),
    .m_axi_mmap_AWQOS(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWQOS),
    .m_axi_mmap_AWREGION(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWREGION),
    .m_axi_mmap_AWUSER(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_AWUSER),
    .m_axi_mmap_WVALID(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WVALID),
    .m_axi_mmap_WREADY(1'b0),
    .m_axi_mmap_WDATA(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WDATA),
    .m_axi_mmap_WSTRB(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WSTRB),
    .m_axi_mmap_WLAST(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WLAST),
    .m_axi_mmap_WID(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WID),
    .m_axi_mmap_WUSER(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_WUSER),
    .m_axi_mmap_ARVALID(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARVALID),
    .m_axi_mmap_ARREADY(mmap_ARREADY),
    .m_axi_mmap_ARADDR(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARADDR),
    .m_axi_mmap_ARID(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARID),
    .m_axi_mmap_ARLEN(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARLEN),
    .m_axi_mmap_ARSIZE(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARSIZE),
    .m_axi_mmap_ARBURST(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARBURST),
    .m_axi_mmap_ARLOCK(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARLOCK),
    .m_axi_mmap_ARCACHE(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARCACHE),
    .m_axi_mmap_ARPROT(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARPROT),
    .m_axi_mmap_ARQOS(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARQOS),
    .m_axi_mmap_ARREGION(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARREGION),
    .m_axi_mmap_ARUSER(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARUSER),
    .m_axi_mmap_RVALID(mmap_RVALID),
    .m_axi_mmap_RREADY(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_RREADY),
    .m_axi_mmap_RDATA(mmap_RDATA),
    .m_axi_mmap_RLAST(1'b0),
    .m_axi_mmap_RID(1'd0),
    .m_axi_mmap_RFIFONUM(mmap_RFIFONUM),
    .m_axi_mmap_RUSER(1'd0),
    .m_axi_mmap_RRESP(2'd0),
    .m_axi_mmap_BVALID(1'b0),
    .m_axi_mmap_BREADY(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_BREADY),
    .m_axi_mmap_BRESP(2'd0),
    .m_axi_mmap_BID(1'd0),
    .m_axi_mmap_BUSER(1'd0),
    .sext_ln13(trunc_ln13_1_reg_157),
    .n(n),
    .stream_din(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_stream_din),
    .stream_full_n(stream_full_n),
    .stream_write(grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_stream_write)
);

Mmap2Stream_mmap_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MMAP_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MMAP_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MMAP_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MMAP_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MMAP_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MMAP_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MMAP_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MMAP_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MMAP_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MMAP_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MMAP_CACHE_VALUE ),
    .USER_DW( 32 ),
    .USER_AW( 64 ))
mmap_m_axi_U(
    .AWVALID(m_axi_mmap_AWVALID),
    .AWREADY(m_axi_mmap_AWREADY),
    .AWADDR(m_axi_mmap_AWADDR),
    .AWID(m_axi_mmap_AWID),
    .AWLEN(m_axi_mmap_AWLEN),
    .AWSIZE(m_axi_mmap_AWSIZE),
    .AWBURST(m_axi_mmap_AWBURST),
    .AWLOCK(m_axi_mmap_AWLOCK),
    .AWCACHE(m_axi_mmap_AWCACHE),
    .AWPROT(m_axi_mmap_AWPROT),
    .AWQOS(m_axi_mmap_AWQOS),
    .AWREGION(m_axi_mmap_AWREGION),
    .AWUSER(m_axi_mmap_AWUSER),
    .WVALID(m_axi_mmap_WVALID),
    .WREADY(m_axi_mmap_WREADY),
    .WDATA(m_axi_mmap_WDATA),
    .WSTRB(m_axi_mmap_WSTRB),
    .WLAST(m_axi_mmap_WLAST),
    .WID(m_axi_mmap_WID),
    .WUSER(m_axi_mmap_WUSER),
    .ARVALID(m_axi_mmap_ARVALID),
    .ARREADY(m_axi_mmap_ARREADY),
    .ARADDR(m_axi_mmap_ARADDR),
    .ARID(m_axi_mmap_ARID),
    .ARLEN(m_axi_mmap_ARLEN),
    .ARSIZE(m_axi_mmap_ARSIZE),
    .ARBURST(m_axi_mmap_ARBURST),
    .ARLOCK(m_axi_mmap_ARLOCK),
    .ARCACHE(m_axi_mmap_ARCACHE),
    .ARPROT(m_axi_mmap_ARPROT),
    .ARQOS(m_axi_mmap_ARQOS),
    .ARREGION(m_axi_mmap_ARREGION),
    .ARUSER(m_axi_mmap_ARUSER),
    .RVALID(m_axi_mmap_RVALID),
    .RREADY(m_axi_mmap_RREADY),
    .RDATA(m_axi_mmap_RDATA),
    .RLAST(m_axi_mmap_RLAST),
    .RID(m_axi_mmap_RID),
    .RUSER(m_axi_mmap_RUSER),
    .RRESP(m_axi_mmap_RRESP),
    .BVALID(m_axi_mmap_BVALID),
    .BREADY(m_axi_mmap_BREADY),
    .BRESP(m_axi_mmap_BRESP),
    .BID(m_axi_mmap_BID),
    .BUSER(m_axi_mmap_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(mmap_ARVALID),
    .I_ARREADY(mmap_ARREADY),
    .I_ARADDR(mmap_ARADDR),
    .I_ARLEN(mmap_ARLEN),
    .I_RVALID(mmap_RVALID),
    .I_RREADY(mmap_RREADY),
    .I_RDATA(mmap_RDATA),
    .I_RFIFONUM(mmap_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(mmap_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(mmap_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(mmap_BVALID),
    .I_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state9) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_ready == 1'b1)) begin
            grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln13_reg_153 <= icmp_ln13_fu_108_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_reg_153 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln13_1_reg_157 <= {{mmap_offset[63:2]}};
    end
end

always @ (*) begin
    if ((grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((stream_full_n == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_153 == 1'd0) & (1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        mmap_ARADDR = sext_ln13_fu_124_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        mmap_ARADDR = grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARADDR;
    end else begin
        mmap_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_153 == 1'd0) & (1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        mmap_ARLEN = shl_ln_fu_138_p3;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        mmap_ARLEN = grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARLEN;
    end else begin
        mmap_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_153 == 1'd0) & (1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        mmap_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        mmap_ARVALID = grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_ARVALID;
    end else begin
        mmap_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        mmap_RREADY = grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_m_axi_mmap_RREADY;
    end else begin
        mmap_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_153 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mmap_blk_n_AR = m_axi_mmap_ARREADY;
    end else begin
        mmap_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        stream_blk_n = stream_full_n;
    end else begin
        stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        stream_din = 65'd18446744073709551616;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        stream_din = grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_stream_din;
    end else begin
        stream_din = grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_stream_din;
    end
end

always @ (*) begin
    if (((stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        stream_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        stream_write = grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_stream_write;
    end else begin
        stream_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln13_reg_153 == 1'd1) & (1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((icmp_ln13_reg_153 == 1'd0) & (1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((stream_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state9 = ap_NS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_io = ((icmp_ln13_reg_153 == 1'd0) & (mmap_ARREADY == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start = grp_Mmap2Stream_Pipeline_VITIS_LOOP_13_1_fu_98_ap_start_reg;

assign icmp_ln13_fu_108_p2 = ((n == 64'd0) ? 1'b1 : 1'b0);

assign sext_ln13_fu_124_p1 = trunc_ln13_1_fu_114_p4;

assign shl_ln_fu_138_p3 = {{trunc_ln13_fu_135_p1}, {1'd0}};

assign trunc_ln13_1_fu_114_p4 = {{mmap_offset[63:2]}};

assign trunc_ln13_fu_135_p1 = n[30:0];

endmodule //Mmap2Stream
