// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Module0Func_Module0Func,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.942090,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=73,HLS_SYN_LUT=197,HLS_VERSION=2022_1}" *)

module Module0Func (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fifo_st_0_din,
        fifo_st_0_full_n,
        fifo_st_0_write,
        fifo_st_1_din,
        fifo_st_1_full_n,
        fifo_st_1_write,
        dram_t1_bank_0_fifo_s_dout,
        dram_t1_bank_0_fifo_s_empty_n,
        dram_t1_bank_0_fifo_s_read,
        dram_t1_bank_0_fifo_peek_dout,
        dram_t1_bank_0_fifo_peek_empty_n,
        dram_t1_bank_0_fifo_peek_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [32:0] fifo_st_0_din;
input   fifo_st_0_full_n;
output   fifo_st_0_write;
output  [32:0] fifo_st_1_din;
input   fifo_st_1_full_n;
output   fifo_st_1_write;
input  [64:0] dram_t1_bank_0_fifo_s_dout;
input   dram_t1_bank_0_fifo_s_empty_n;
output   dram_t1_bank_0_fifo_s_read;
input  [64:0] dram_t1_bank_0_fifo_peek_dout;
input   dram_t1_bank_0_fifo_peek_empty_n;
output   dram_t1_bank_0_fifo_peek_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[32:0] fifo_st_0_din;
reg fifo_st_0_write;
reg[32:0] fifo_st_1_din;
reg fifo_st_1_write;
reg dram_t1_bank_0_fifo_s_read;
reg dram_t1_bank_0_fifo_peek_read;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    fifo_st_0_blk_n;
wire    ap_CS_fsm_state4;
reg    fifo_st_1_blk_n;
wire    grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start;
wire    grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_done;
wire    grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_idle;
wire    grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_ready;
wire   [32:0] grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_0_din;
wire    grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_0_write;
wire   [32:0] grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_1_din;
wire    grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_1_write;
wire    grp_Module0Func_Pipeline_module_0_epoch_fu_86_dram_t1_bank_0_fifo_s_read;
wire    grp_Module0Func_Pipeline_module_0_epoch_fu_86_dram_t1_bank_0_fifo_peek_read;
reg    grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_block_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start_reg = 1'b0;
end

Module0Func_Module0Func_Pipeline_module_0_epoch grp_Module0Func_Pipeline_module_0_epoch_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start),
    .ap_done(grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_done),
    .ap_idle(grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_idle),
    .ap_ready(grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_ready),
    .fifo_st_0_din(grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_0_din),
    .fifo_st_0_full_n(fifo_st_0_full_n),
    .fifo_st_0_write(grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_0_write),
    .fifo_st_1_din(grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_1_din),
    .fifo_st_1_full_n(fifo_st_1_full_n),
    .fifo_st_1_write(grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_1_write),
    .dram_t1_bank_0_fifo_s_dout(dram_t1_bank_0_fifo_s_dout),
    .dram_t1_bank_0_fifo_s_empty_n(dram_t1_bank_0_fifo_s_empty_n),
    .dram_t1_bank_0_fifo_s_read(grp_Module0Func_Pipeline_module_0_epoch_fu_86_dram_t1_bank_0_fifo_s_read),
    .dram_t1_bank_0_fifo_peek_dout(dram_t1_bank_0_fifo_peek_dout),
    .dram_t1_bank_0_fifo_peek_empty_n(dram_t1_bank_0_fifo_peek_empty_n),
    .dram_t1_bank_0_fifo_peek_read(grp_Module0Func_Pipeline_module_0_epoch_fu_86_dram_t1_bank_0_fifo_peek_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_ready == 1'b1)) begin
            grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        dram_t1_bank_0_fifo_peek_read = grp_Module0Func_Pipeline_module_0_epoch_fu_86_dram_t1_bank_0_fifo_peek_read;
    end else begin
        dram_t1_bank_0_fifo_peek_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        dram_t1_bank_0_fifo_s_read = grp_Module0Func_Pipeline_module_0_epoch_fu_86_dram_t1_bank_0_fifo_s_read;
    end else begin
        dram_t1_bank_0_fifo_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fifo_st_0_blk_n = fifo_st_0_full_n;
    end else begin
        fifo_st_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        fifo_st_0_din = 33'd4294967296;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_st_0_din = grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_0_din;
    end else begin
        fifo_st_0_din = grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_0_din;
    end
end

always @ (*) begin
    if ((~((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        fifo_st_0_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_st_0_write = grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_0_write;
    end else begin
        fifo_st_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fifo_st_1_blk_n = fifo_st_1_full_n;
    end else begin
        fifo_st_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        fifo_st_1_din = 33'd4294967296;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_st_1_din = grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_1_din;
    end else begin
        fifo_st_1_din = grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_1_din;
    end
end

always @ (*) begin
    if ((~((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        fifo_st_1_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_st_1_write = grp_Module0Func_Pipeline_module_0_epoch_fu_86_fifo_st_1_write;
    end else begin
        fifo_st_1_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4 = ((fifo_st_1_full_n == 1'b0) | (fifo_st_0_full_n == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start = grp_Module0Func_Pipeline_module_0_epoch_fu_86_ap_start_reg;

endmodule //Module0Func
