puts "applying partitioning constraints generated by tapac"
write_checkpoint before_add_floorplan_constraints.dcp

# begin defining a slot
create_pblock CR_X4Y0_To_CR_X7Y3
resize_pblock CR_X4Y0_To_CR_X7Y3 -add CLOCKREGION_X4Y0:CLOCKREGION_X7Y3
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X4Y0_To_CR_X7Y3 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11


# begin defining a slot
create_pblock CR_X0Y8_To_CR_X3Y11
resize_pblock CR_X0Y8_To_CR_X3Y11 -add CLOCKREGION_X0Y8:CLOCKREGION_X3Y11
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X0Y8_To_CR_X3Y11 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11


# begin defining a slot
create_pblock CR_X0Y0_To_CR_X3Y3
resize_pblock CR_X0Y0_To_CR_X3Y3 -add CLOCKREGION_X0Y0:CLOCKREGION_X3Y3
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X0Y0_To_CR_X3Y3 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11


# begin defining a slot
create_pblock CR_X0Y4_To_CR_X3Y7
resize_pblock CR_X0Y4_To_CR_X3Y7 -add CLOCKREGION_X0Y4:CLOCKREGION_X3Y7
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X0Y4_To_CR_X3Y7 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11


# begin defining a slot
create_pblock CR_X4Y4_To_CR_X7Y7
resize_pblock CR_X4Y4_To_CR_X7Y7 -add CLOCKREGION_X4Y4:CLOCKREGION_X7Y7
# remove the reserved clock regions for the Vitis infra
resize_pblock CR_X4Y4_To_CR_X7Y7 -remove CLOCKREGION_X7Y1:CLOCKREGION_X7Y11

add_cells_to_pblock [get_pblocks CR_X0Y0_To_CR_X3Y3] [get_cells -regex {
  level0_i/ulp/.*/inst/.*/Mmap2Stream_out_0
  level0_i/ulp/.*/inst/.*/Mmap2Stream_out_id_0
  level0_i/ulp/.*/inst/.*/Stream2Mmap_out_0
  level0_i/ulp/.*/inst/.*/Stream2Mmap_out_1
  level0_i/ulp/.*/inst/.*/Stream2Mmap_out_id_0
  level0_i/ulp/.*/inst/.*/Stream2Mmap_out_id_1
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_6_0
  level0_i/ulp/.*/inst/.*/in_6__m_axi
  level0_i/ulp/.*/inst/.*/L1_out_dist_0/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_dist_1/inst\\[2]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_id_0/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_id_1/inst\\[2]\\.unit
  level0_i/ulp/.*/inst/.*/out_dist_6/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/out_id_6/inst\\[0]\\.unit
} ]
add_cells_to_pblock [get_pblocks CR_X4Y0_To_CR_X7Y3] [get_cells -regex {
  level0_i/ulp/.*/inst/.*/Stream2Mmap_out_2
  level0_i/ulp/.*/inst/.*/Stream2Mmap_out_3
  level0_i/ulp/.*/inst/.*/Stream2Mmap_out_id_2
  level0_i/ulp/.*/inst/.*/Stream2Mmap_out_id_3
  level0_i/ulp/.*/inst/.*/krnl_globalSort_L1_L2_2
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_7_0
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_8_0
  level0_i/ulp/.*/inst/.*/in_7__m_axi
  level0_i/ulp/.*/inst/.*/in_8__m_axi
  level0_i/ulp/.*/inst/.*/L1_out_dist_2/.*.unit
  level0_i/ulp/.*/inst/.*/L1_out_dist_3/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_id_2/.*.unit
  level0_i/ulp/.*/inst/.*/L1_out_id_3/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/out_dist_6/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/out_dist_7/.*.unit
  level0_i/ulp/.*/inst/.*/out_dist_8/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_6/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/out_id_7/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_8/.*.unit
} ]
add_cells_to_pblock [get_pblocks CR_X0Y4_To_CR_X3Y7] [get_cells -regex {
  level0_i/ulp/.*/inst/.*/krnl_globalSort_L1_L2_0
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_0_0
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_1_0
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_11_0
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_2_0
  level0_i/ulp/.*/inst/.*/in_0__m_axi
  level0_i/ulp/.*/inst/.*/in_1__m_axi
  level0_i/ulp/.*/inst/.*/in_11__m_axi
  level0_i/ulp/.*/inst/.*/in_2__m_axi
  level0_i/ulp/.*/inst/.*/L1_out_dist_0/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_dist_1/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_id_0/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_id_1/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/out_dist_0/.*.unit
  level0_i/ulp/.*/inst/.*/out_dist_11/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/out_dist_1/.*.unit
  level0_i/ulp/.*/inst/.*/out_dist_2/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_0/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_11/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/out_id_1/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_2/.*.unit
} ]
add_cells_to_pblock [get_pblocks CR_X0Y8_To_CR_X3Y11] [get_cells -regex {
  level0_i/ulp/.*/inst/.*/krnl_globalSort_L1_L2_1
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_3_0
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_4_0
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_5_0
  level0_i/ulp/.*/inst/.*/in_3__m_axi
  level0_i/ulp/.*/inst/.*/in_4__m_axi
  level0_i/ulp/.*/inst/.*/in_5__m_axi
  level0_i/ulp/.*/inst/.*/L1_out_dist_1/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_id_1/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/out_dist_3/.*.unit
  level0_i/ulp/.*/inst/.*/out_dist_4/.*.unit
  level0_i/ulp/.*/inst/.*/out_dist_5/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_3/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_4/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_5/.*.unit
} ]
add_cells_to_pblock [get_pblocks CR_X4Y4_To_CR_X7Y7] [get_cells -regex {
  level0_i/ulp/.*/inst/.*/krnl_globalSort_L1_L2_3
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_10_0
  level0_i/ulp/.*/inst/.*/krnl_partialKnn_wrapper_9_0
  level0_i/ulp/.*/inst/.*/in_10__m_axi
  level0_i/ulp/.*/inst/.*/in_9__m_axi
  level0_i/ulp/.*/inst/.*/L1_out_dist_3/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/L1_out_id_3/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/.*/out_dist_10/.*.unit
  level0_i/ulp/.*/inst/.*/out_dist_11/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/out_dist_9/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_10/.*.unit
  level0_i/ulp/.*/inst/.*/out_id_11/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/.*/out_id_9/.*.unit
} ]
add_cells_to_pblock [get_pblocks CR_X0Y0_To_CR_X3Y3] [get_cells -regex {
  level0_i/ulp/.*/inst/temp5/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp5/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp7/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp7/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp6/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp6/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp8/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp8/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_0/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_0/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_0/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_1/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_1/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_1/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_10/AR_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_10/AW_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_10/W_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_11/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_11/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_11/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_2/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_2/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_2/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_3/AR_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_3/AW_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_3/W_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_4/AR_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_4/AW_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_4/W_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_5/AR_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_5/AW_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_5/W_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_7/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_7/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_7/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_8/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_8/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_8/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_9/AR_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_9/AW_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_9/W_pipeline/inst\\[1]\\.unit
} ]
add_cells_to_pblock [get_pblocks CR_X4Y0_To_CR_X7Y3] [get_cells -regex {
  level0_i/ulp/.*/inst/temp5/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp5/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp5/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp7/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp7/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp7/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp6/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp6/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp6/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp8/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp8/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/temp8/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_10/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_10/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_10/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_10/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_10/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_7/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_7/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_8/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_8/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_9/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_9/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_9/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_9/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_9/W_pipeline/inst\\[0]\\.unit
} ]
add_cells_to_pblock [get_pblocks CR_X0Y4_To_CR_X3Y7] [get_cells -regex {
  level0_i/ulp/.*/inst/in_0/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_0/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_1/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_1/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_11/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_11/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_2/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_2/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_3/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_3/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_3/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_3/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_3/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_4/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_4/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_4/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_4/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_4/W_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_5/R_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_5/B_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_5/AR_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_5/AW_pipeline/inst\\[0]\\.unit
  level0_i/ulp/.*/inst/in_5/W_pipeline/inst\\[0]\\.unit
} ]
add_cells_to_pblock [get_pblocks CR_X4Y4_To_CR_X7Y7] [get_cells -regex {
  level0_i/ulp/.*/inst/in_10/R_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_10/B_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_9/R_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_9/B_pipeline/inst\\[1]\\.unit
} ]
add_cells_to_pblock [get_pblocks CR_X0Y8_To_CR_X3Y11] [get_cells -regex {
  level0_i/ulp/.*/inst/in_3/R_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_3/B_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_4/R_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_4/B_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_5/R_pipeline/inst\\[1]\\.unit
  level0_i/ulp/.*/inst/in_5/B_pipeline/inst\\[1]\\.unit
} ]
foreach pblock [get_pblocks -regexp CR_X\\d+Y\\d+_To_CR_X\\d+Y\\d+] {
  if {[get_property CELL_COUNT $pblock] == 0} {
    puts "WARNING: delete empty pblock $pblock "
    delete_pblocks $pblock
  }
}
foreach pblock [get_pblocks] {
  report_utilization -pblocks $pblock
}
